gpg: C5C84658CCFD7E8E71DEE933AF3AE54FC3A35C9F
url: "https://repo.moth.contact"

deb:
  origin: "asciimoth"
  label: "asciimoth"
  name: "asciimoth"
  description: "ASCII Moth's personal APT and RPM repo"

rpm:
  name: "asciimoth"

